# Generated by Django 5.0.2 on 2024-02-29 07:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
