# Generated by Django 5.0.2 on 2024-02-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_transaksi_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
