# Generated by Django 5.0.2 on 2024-03-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_transaksi_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='harga',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='pembayaran',
        ),
    ]
