# Generated by Django 5.0.2 on 2024-03-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_transaksi_harga_remove_transaksi_pembayaran'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaksi',
            name='jenis_pembayaran',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='transaksi',
            name='tanggal',
        ),
        migrations.AddField(
            model_name='transaksi',
            name='harga',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
