# Generated by Django 5.0.2 on 2024-03-01 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_transaksi_jenis_pembayaran'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='pembayaran',
            field=models.CharField(choices=[('lunas', 'Lunas'), ('belum_lunas', 'Belum Lunas')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
