# Generated by Django 5.0.2 on 2024-03-01 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_transaksi_tanggal'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='status',
            field=models.CharField(choices=[('baru', 'Baru'), ('proses', 'Proses'), ('selesai', 'Selesai'), ('telah_diambil', 'Telah Diambil')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
