# Generated by Django 5.0.2 on 2024-03-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_transaksi_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaksi',
            name='selesai',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
